---
- hosts: edxsanboxapi
  become: yes
  gather_facts: false
  vars:
    destDir: /home/ubuntu/citynex-beta/citynex-api-beta/helmtemplate
    root: /home/ubuntu/citynex-beta/citynex-api-beta
    envDir: /home/ubuntu/citynex-beta/citynex-api-beta/helmtemplate/env
  tasks:

    - name: Chart Update
      command: "{{ item }} chdir={{destDir}}"
      become: true
      become_user: ubuntu
      with_items:
        - /usr/local/bin/yq e '.name = "{{ProjectName}}"' -i Chart.yaml
        - /usr/local/bin/yq e '.appVersion = "{{tag}}"' -i Chart.yaml
        - /bin/bash {{root}}/collect_host_alias.sh {{root}}
      tags:
        - chart
