name: Docker Build and Push

on:
  push:
    branches:
      - master
      - beta

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    # - name: Login to GitHub Container Registry
    #   env:
    #     CR_PAT_SECRET: ${{ secrets.CR_PAT }}
    #   run: echo $CR_PAT_SECRET | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set image tags
      id: vars
      run: |
        echo "commit_sha=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV


    # - name: Build and Push Docker Image
    #   env:
    #     REPO_NAME: ${{ github.event.repository.name }}
    #     BRANCH_NAME: ${{ github.ref_name }}
    #   run: |
    #     docker build -t ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-${BRANCH_NAME}:${{ env.commit_sha }} .
    #     docker push ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-${BRANCH_NAME}:${{ env.commit_sha }}


    # - name: Install Ansible
    #   shell: bash
    #   run: |
    #     sudo apt update
    #     sudo apt install -y ansible
    #     ansible --version

    # - name: Set up SSH
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ vars.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     echo "${{ vars.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
    #     chmod 600 ~/.ssh/id_rsa
    #     chmod 644 ~/.ssh/id_rsa.pub
    #     ssh-keyscan -p 30111 -H 80.248.196.125 >> ~/.ssh/known_hosts

    #     ssh -o StrictHostKeyChecking=no -p 30111 ubuntu@80.248.196.125

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 80.248.196.125
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 30111
        script: whoami

    - name: Run Ansible Playbook
      env:
        ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
        ANSIBLE_HOST_KEY_CHECKING: False
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        cat ~/.ssh/id_rsa.pub
        ansible-playbook -i inventory/hosts.ini playbooks/main.yml -e tag=${{ env.commit_sha }} -e ProjectName=${REPO_NAME}