name: Build, Test, and Deploy

on:
  push:
    branches: 
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Build Stage
        run: echo "Running Build Stage"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print Test Stage
        run: echo "Running Test Stage"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print Deploy Stage
        run: exit 1
